### ISSUE TITLE
Refuso "siaiscritto" invece di "sia iscritto"

### ISSUE THREAD

**Issue by alessandro-gentilini** [fkomauli/riforma-costituzionale#12]
https://github.com/fkomauli/riforma-costituzionale/blob/renzi-boschi/Costituzione#L387 riporta il refuso "siaiscritto" invece del corretto "sia iscritto".

Il refuso e` presente anche qui http://www.gazzettaufficiale.it/atto/serie_generale/caricaArticolo?art.progressivo=0&art.idArticolo=12&art.versione=1&art.codiceRedazionale=16A03075&art.dataPubblicazioneGazzetta=2016-04-15&art.idGruppo=1&art.idSottoArticolo1=10&art.idSottoArticolo=1&art.flagTipoArticolo=0#art

**Comment by fkomauli** [comment]
Grazie dell'osservazione! Non conosco le procedure istituzionali di correzione dei typo nei testi di legge costituzionale, hai per caso qualche informazione? Si tratta di un errore già noto ai legislatori o l'hai scoperto tu stesso? Riguarda solo la versione online della gazzetta ufficiale? Altri testi di confronto non riportano l'errore, non so se corretto da chi li ha scritti o non presente in altre fonti.

**Comment by alessandro-gentilini** [comment]
Ciao, non so rispondere a nessuna delle tue domande. Ho un vago ricordo di scuola secondo il quale e` la versione stampata della Gazzetta Ufficiale che costituisce il riferimento ufficiale.

**Comment by fkomauli** [comment]
Corretto in ogni caso il refuso, dubito che per un typo ci debbano essere chissà che procedure istituzionali. Se ci sarà il merge credo che semplicemente lo correggeranno.
